### ISSUE TITLE
Closing all windows by pressing Delete button

### ISSUE THREAD

**Issue by Razip** [OpenRCT2/OpenLoco#115]
The title speaks for itself.

**Comment by jgottula** [comment]
The vanilla game already has this ability: instead of hitting backspace to close the current window, you hit shift+backspace and all windows are closed.

This is documented on page 11 of the game manual. The digital versions of the game supply a PDF of the manual in the folder where the game's installed.

Or if you're like me and you bought a physical copy of the game back in like 2004, it's in the manual book that comes with the CD case. In fact here's a photograph from my copy:

![RTFM](https://user-images.githubusercontent.com/822207/36339557-85434ef0-137d-11e8-88d4-853e6e6a6c8a.jpg)

**Comment by jgottula** [comment]
Pardon the upside-down-ness; apparently GitHub's image preview code doesn't understand EXIF image rotation information, which is pretty idiotic. If you open the full-size image, it should most likely render right-side-up.

**Comment by Razip** [comment]
It worked, thank you!
